### ISSUE TITLE
How to install this library in my Toit v2?

### ISSUE THREAD

**Issue by HKPhysicist** [toitware/cellular#34]
Dear Developer Friends,
Now, I have a working Toit v2 installed under /opt/toit-sdk/ from sources.  I ran these examples successfully:
/opt/toit-sdk/bin/toit.run /usr/local/src/toit/examples/hello.toit
/opt/toit-sdk/bin/toit.run /usr/local/src/toit/examples/mandelbrot.toit

Then, what are the next steps to install this Toit Cellular library, and probably other library, in my present Toit v2 installation?

Yours faithfully,
Timmy

**Comment by floitsch** [comment]
The easiest is probably to follow the cellular tutorial: https://docs.toit.io/tutorials/network/cellular
